from pathlib import Path
import re
from pypdf import PdfReader


REQUIRED_TITLE = "Philippines Mission Intel Status Report"
REQUIRED_SECTIONS = [
    "Strategic Situation",
    "Priority Intelligence",
    "U.S. Embassy (Manila) travel advisories",
    "U.S. State Department travel advisories for Americans",
    "Health / Environmental Risk",
    "Weather forecast",
    "NAIA / airport operational status"
]


class ReportValidationError(Exception):
    pass


def extract_pdf_text(pdf_path: str) -> tuple[str, int, int]:
    path = Path(pdf_path)

    if not path.exists():
        raise ReportValidationError(f"PDF not found: {pdf_path}")

    file_size = path.stat().st_size
    if file_size < 2000:
        raise ReportValidationError(f"PDF too small to trust: {file_size} bytes")

    try:
        reader = PdfReader(pdf_path)
    except Exception as e:
        raise ReportValidationError(f"PDF unreadable: {e}") from e

    page_count = len(reader.pages)

    text_parts = []
    for page in reader.pages:
        text_parts.append(page.extract_text() or "")

    text = "\n".join(text_parts).strip()
    if not text:
        raise ReportValidationError("Extracted PDF text is empty")

    return text, page_count, file_size


def word_count(text: str) -> int:
    return len(re.findall(r"\b\w+\b", text))


def normalize_for_match(text: str) -> str:
    return "".join(str(text or "").lower().split())

def validate_report_text(text: str) -> dict:
    normalized_text = normalize_for_match(text)
    normalized_title = normalize_for_match(REQUIRED_TITLE)

    print("DEBUG normalized PDF sample:", normalized_text[:300])  

    title_found = any(
        normalize_for_match(REQUIRED_TITLE) in normalize_for_match(page_text)
        for page_text in text.split("\n")
    )

    if not title_found:
        raise ReportValidationError("Missing required report title")

    normalized_text = normalize_for_match(text)

    missing_sections = [
        section
        for section in REQUIRED_SECTIONS
        if normalize_for_match(section) not in normalized_text
    ]
    if missing_sections:
        raise ReportValidationError(
            f"Missing required sections: {', '.join(missing_sections)}"
        )

    wc = word_count(text)
    if wc < 700:
        raise ReportValidationError(f"Word count below threshold: {wc}")

    if normalize_for_match("Generated by 0001Z daily") not in normalized_text:
        raise ReportValidationError("Missing required generation-time label")

    forbidden_placeholders = ["TODO", "TBD", "INSERT HERE"]
    for token in forbidden_placeholders:
        if token in text:
            raise ReportValidationError(f"Placeholder text found: {token}")

    return {
        "title_found": True,
        "sections_checked": len(REQUIRED_SECTIONS),
        "word_count": wc,
    }


def validate_report_pdf(pdf_path: str) -> dict:
    text, page_count, file_size = extract_pdf_text(pdf_path)

    if page_count < 2:
        raise ReportValidationError(f"PDF page count too low: {page_count}")

    return {
        "ok": True,
        "page_count": page_count,
        "file_size_bytes": file_size,
    }

   